# Generated by Django 3.1.3 on 2020-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201120_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='registr',
            name='age',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
