# Generated by Django 3.1.3 on 2020-11-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201120_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('dob', models.EmailField(max_length=254)),
                ('activate', models.BooleanField()),
            ],
        ),
    ]
